### ISSUE TITLE
Interop issues between msgpack-java (0.6.8 and 0.6.11 tested) and msgpack-cli (0.5.5 and 0.4.1 tested) 

### ISSUE THREAD

**Issue by jameswm** [msgpack/msgpack-java#141] opened 2014-10-15 22:23 UTC
I have yet to find a way to serialize anything other than trivial object graphs from msgpack-java and have them successfully deserialize using msgpack-cli.  I have tried all combinations of msgpack-java 0.6.8 and 0.6.11 and msgpack-cli 0.4.1 and 0.5.5.  Obviously, it doesn't work in the other direction either, from csharp to java.

Here are two java classes that successfully interop (note that the Submission.queueName field is commented out in the classes and the tests:

	import org.msgpack.annotation.Message;

	@Message
	public class SubmitterId
	{
		public String machineName;
		public String submitterName;
		public String submitterVersion;
	}

	@Message
	public class Submission
	{
		public SubmitterId  submitterId;
		//public String       queueName;
	}

Here are the equivalent classes in csharp:

    public class SubmitterId
    {
        public String machineName;
        public String submitterName;
        public String submitterVersion;
    }

    public class Submission
    {
        public SubmitterId submitterId;
        //public String queueName;
    }

Here is the java serialization code I used to serialize:

        MessagePack mp = new MessagePack();

        OutputStream file = new FileOutputStream("c:\\submission-java.dat");
        SubmitterId sid = new SubmitterId();
        sid.machineName="MACHINE_NAME";
        sid.submitterName="SubmitterTests";
        sid.submitterVersion = "1.0";
        Submission s = new Submission();
        //s.queueName = "test-queue";
        s.submitterId = sid;
        mp.write( file, s );

Here is the csharp code to deserialize:

            var msgPack = MessagePackSerializer.Create<Submission>();
            using ( var stream = new FileStream( @"c:\submission-java.dat", FileMode.Open ) )
            {
                Submission s = msgPack.Unpack( stream );
                //Assert.AreEqual( s.queueName, "test-queue" );
                Assert.AreEqual( s.submitterId.machineName, "MACHINE_NAME" );
                Assert.AreEqual( s.submitterId.submitterName, "SubmitterTests" );
                Assert.AreEqual( s.submitterId.submitterVersion, "1.0" );
            }

With the above version of these classes, the serialization and deserialization complete without errors, and all the expected fields have all the expected values.

However, the deserialization in csharp fails when I remove the comments from the "queueName" field in the classes and tests.  As soon as I do that, I get the following exception when deserializing using msgpack-cli:

	Result Message:	
	System.Runtime.Serialization.SerializationException : Cannot deserialize member 'queueName' of type 'Messages.Msgpack.Submission'.
	  ----> MsgPack.MessageTypeException : Cannot convert 'System.String' type value from type 'FixedArray'(0x93).
	Result StackTrace:	
	at MsgPack.Serialization.EmittingSerializers.Generated.Messages_Msgpack_SubmissionSerializer0.UnpackFromCore(Unpacker )
	at MsgPack.Serialization.MessagePackSerializer`1.UnpackFrom(Unpacker unpacker)
	at MsgPack.Serialization.AutoMessagePackSerializer`1.UnpackFromCore(Unpacker unpacker)
	at MsgPack.Serialization.MessagePackSerializer`1.UnpackFrom(Unpacker unpacker)
	at MsgPack.Serialization.MessagePackSerializer`1.Unpack(Stream stream)
	at JPTest.SubmitterTests.readSerializedSubmissionFromFile() in c:\MessagePackCli\Test\SubmitterTests.cs:line 98
	--MessageTypeException
	at MsgPack.ItemsUnpacker.ReadString(String& result)
	at MsgPack.Serialization.EmittingSerializers.Generated.Messages_Msgpack_SubmissionSerializer0.UnpackFromCore(Unpacker )

For what it's worth, here is the error I get when trying to deserialize this same object graph in msgpack-java after serialization from csharp:

	org.msgpack.MessageTypeException: Expected array, but got raw value
		at org.msgpack.unpacker.Accept.acceptRaw(Accept.java:73)
		at org.msgpack.unpacker.MessagePackUnpacker.readOneWithoutStack(MessagePackUnpacker.java:112)
		at org.msgpack.unpacker.MessagePackUnpacker.readOne(MessagePackUnpacker.java:73)
		at org.msgpack.unpacker.MessagePackUnpacker.readArrayBegin(MessagePackUnpacker.java:478)
		at com.messages.msgpack.SubmitterId_$$_Template_23910357_0.read(SubmitterId_$$_Template_23910357_0.java)
		at org.msgpack.template.AbstractTemplate.read(AbstractTemplate.java:31)
		at com.messages.msgpack.Submission_$$_Template_23910357_1.read(Submission_$$_Template_23910357_1.java)
		at org.msgpack.template.AbstractTemplate.read(AbstractTemplate.java:31)
		at org.msgpack.MessagePack.read(MessagePack.java:527)
		at org.msgpack.MessagePack.read(MessagePack.java:511)
		at com.msgpack.test.SubmissionTests.submissionDeserializesFromCSharpFile(SubmissionTests.java:26)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
		at java.lang.reflect.Method.invoke(Method.java:597)
		at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
		at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
		at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
		at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
		at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
		at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
		at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
		at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

Are these language-specific implementations of MessagePack tested against each other for interoperability?  Should this simple case be working?  Am I using the libraries correctly?

**Comment by komamitsu** [comment] 2015-05-03 15:18
@jameswm Sorry for late reply. The root cause seems that MessagePack earlier than v0.7.x serializes a bean as an array in MessagePack format https://github.com/msgpack/msgpack-java/blob/master/src/main/java/org/msgpack/template/builder/ReflectionTemplateBuilder.java#L99-L116. 
According to the error message that occurred in csharp, msgpack-cli looks to handle a bean (an object in csharp) as a sequence of primitives (in this case, 3 Strings). Serializing bean can depend on each language specification. So it's better to convert beans to Map or Array in MessagePack explicitly just in case when passing MessagePack data over cross platforms.

**Comment by komamitsu** [comment] 2015-05-17 06:12
I'm closing this issue. Please re-open it if you still have any problem.

**Closed by komamitsu** 2015-05-17 06:12 UTC
